# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (every hour, between 07:00 and 23:00.)
  schedule: [{cron: "0 7-23 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: renatocfrancisco
          template: classic
          base: header, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 6
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 5
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_music: yes
          plugin_music_token: ${{ secrets.MUSIC_METRICS_TOKEN }}
          plugin_music_limit: 3
          plugin_music_mode: recent
          plugin_music_provider: lastfm
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_user: renatocfrancisc
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_METRICS_TOKEN }}
          plugin_steam_user: ${{ secrets.STEAM_ID_METRICS }}
          plugin_steam_achievements_limit: 2
          plugin_steam_games_limit: 1
          plugin_steam_playtime_threshold: 2
          plugin_steam_recent_games_limit: 1
          plugin_steam_sections: player, recently-played
